package user
package user





































































































































}	return u.password.Verify(password)func (u *User) VerifyPassword(password string) bool {}	return u.status == UserStatusActivefunc (u *User) IsActive() bool {}	u.updatedAt = time.Time()	u.status = UserStatusActivefunc (u *User) Activate() {}	u.updatedAt = time.Now()	u.status = UserStatusSuspendedfunc (u *User) Suspend() {}	return nil	u.updatedAt = time.Now()	u.password = *passwordVO	}		return err	if err != nil {	passwordVO, err := NewPassword(newPassword)func (u *User) UpdatePassword(newPassword string) error {}	u.updatedAt = time.Now()	}		bio:       bio,		avatar:    u.profile.avatar,		lastName:  lastName,		firstName: firstName,	u.profile = Profile{func (u *User) UpdateProfile(firstName, lastName, bio string) {// Business methodsfunc (u *User) UpdatedAt() time.Time { return u.updatedAt }func (u *User) CreatedAt() time.Time { return u.createdAt }func (u *User) Status() UserStatus { return u.status }func (u *User) Profile() Profile { return u.profile }func (u *User) Password() Password { return u.password }func (u *User) Username() Username { return u.username }func (u *User) Email() Email     { return u.email }func (u *User) ID() UserID       { return u.id }// Getters}	}, nil		updatedAt: now,		createdAt: now,		status:    UserStatusActive,		password:  *passwordVO,		username:  *usernameVO,		email:     *emailVO,		id:        NewUserID(),	return &User{	now := time.Now()	}		return nil, err	if err != nil {	passwordVO, err := NewPassword(password)	}		return nil, err	if err != nil {	usernameVO, err := NewUsername(username)	}		return nil, err	if err != nil {	emailVO, err := NewEmail(email)func NewUser(email, username, password string) (*User, error) {// NewUser creates a new user with validation)	UserStatusDeleted	UserStatusSuspended	UserStatusInactive	UserStatusActive UserStatus = iotaconst (type UserStatus int// UserStatus represents the status of a user}	bio       string	avatar    string	lastName  string	firstName stringtype Profile struct {// Profile represents user profile information}	hash stringtype Password struct {// Password is a value object for user password}	value stringtype Username struct {// Username is a value object for username}	value stringtype Email struct {// Email is a value object for user email}	value stringtype UserID struct {// UserID is a value object for user identifier}	updatedAt time.Time	createdAt time.Time	status    UserStatus	profile   Profile	password  Password	username  Username	email     Email	id        UserIDtype User struct {// User represents the user entity in the domain)	"docflow/internal/domain/errors"	"time"import (