package user
package user

import (












































































































































































}	}		return UserStatusInactive	default:		return UserStatusDeleted	case "deleted":		return UserStatusSuspended	case "suspended":		return UserStatusInactive	case "inactive":		return UserStatusActive	case "active":	switch strings.ToLower(status) {func UserStatusFromString(status string) UserStatus {}	}		return "unknown"	default:		return "deleted"	case UserStatusDeleted:		return "suspended"	case UserStatusSuspended:		return "inactive"	case UserStatusInactive:		return "active"	case UserStatusActive:	switch s {func (s UserStatus) String() string {// UserStatus methods}	return strings.TrimSpace(fmt.Sprintf("%s %s", p.firstName, p.lastName))func (p Profile) FullName() string {func (p Profile) Bio() string       { return p.bio }func (p Profile) Avatar() string    { return p.avatar }func (p Profile) LastName() string  { return p.lastName }func (p Profile) FirstName() string { return p.firstName }}	}		bio:       strings.TrimSpace(bio),		avatar:    strings.TrimSpace(avatar),		lastName:  strings.TrimSpace(lastName),		firstName: strings.TrimSpace(firstName),	return Profile{func NewProfile(firstName, lastName, avatar, bio string) Profile {// Profile value object methods}	return err == nil	err := bcrypt.CompareHashAndPassword([]byte(p.hash), []byte(password))func (p Password) Verify(password string) bool {}	return p.hashfunc (p Password) Hash() string {}	return &Password{hash: hash}func NewPasswordFromHash(hash string) *Password {// NewPasswordFromHash creates password from existing hash}	return &Password{hash: string(hash)}, nil	}		return nil, fmt.Errorf("failed to hash password: %w", err)	if err != nil {	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)	// Hash the password	}		return nil, errors.NewValidationError("password must be at least 8 characters long")	if len(password) < 8 {	}		return nil, errors.NewValidationError("password cannot be empty")	if password == "" {func NewPassword(password string) (*Password, error) {// NewPassword creates and validates password value object}	return u.value == other.valuefunc (u Username) Equals(other Username) bool {}	return u.valuefunc (u Username) String() string {}	return &Username{value: username}, nil	}		return nil, errors.NewValidationError("username can only contain letters, numbers, underscores, and hyphens")	if !usernameRegex.MatchString(username) {	usernameRegex := regexp.MustCompile(`^[a-zA-Z0-9_-]+$`)	// Username can only contain letters, numbers, underscores, and hyphens	}		return nil, errors.NewValidationError("username must be no more than 30 characters long")	if len(username) > 30 {	}		return nil, errors.NewValidationError("username must be at least 3 characters long")	if len(username) < 3 {	}		return nil, errors.NewValidationError("username cannot be empty")	if username == "" {		username = strings.TrimSpace(username)func NewUsername(username string) (*Username, error) {// NewUsername creates and validates username value object}	return e.value == other.valuefunc (e Email) Equals(other Email) bool {}	return e.valuefunc (e Email) String() string {}	return &Email{value: email}, nil	}		return nil, errors.NewValidationError("invalid email format")	if !emailRegex.MatchString(email) {	emailRegex := regexp.MustCompile(`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`)	// Simple email validation regex	}		return nil, errors.NewValidationError("email cannot be empty")	if email == "" {		email = strings.TrimSpace(strings.ToLower(email))func NewEmail(email string) (*Email, error) {// NewEmail creates and validates email value object}	return id.value == other.valuefunc (id UserID) Equals(other UserID) bool {}	return id.valuefunc (id UserID) String() string {}	return UserID{value: id}, nil	}		return UserID{}, errors.NewValidationError("user ID cannot be empty")	if id == "" {func NewUserIDFromString(id string) (UserID, error) {// NewUserIDFromString creates UserID from string}	return UserID{value: hex.EncodeToString(bytes)}	rand.Read(bytes)	bytes := make([]byte, 16)func NewUserID() UserID {// NewUserID generates a new unique user ID)	"docflow/internal/domain/errors"	"golang.org/x/crypto/bcrypt"	"strings"	"regexp"	"fmt"	"encoding/hex"	"crypto/rand"